-- ============================================================
--  Ferrafoni Home Planner - migrazione: catalogo prodotti
--  Da eseguire UNA VOLTA SOLA sul database gia in uso.
--  Aggiunge il catalogo che assegna da solo il reparto agli
--  articoli della spesa, anche a quelli dettati dall'iPhone.
-- ============================================================

CREATE TABLE IF NOT EXISTS catalogo (
  id            INTEGER PRIMARY KEY AUTOINCREMENT,
  nome          TEXT NOT NULL,
  nome_cerca    TEXT NOT NULL,
  categoria_id  TEXT REFERENCES categorie(id),
  usi           INTEGER NOT NULL DEFAULT 0
);
CREATE UNIQUE INDEX IF NOT EXISTS idx_catalogo_nome ON catalogo(nome_cerca);

INSERT OR IGNORE INTO catalogo (nome, nome_cerca, categoria_id) VALUES ('Mele', 'mele', 'sp_ortofrutta');
INSERT OR IGNORE INTO catalogo (nome, nome_cerca, categoria_id) VALUES ('Pere', 'pere', 'sp_ortofrutta');
INSERT OR IGNORE INTO catalogo (nome, nome_cerca, categoria_id) VALUES ('Banane', 'banane', 'sp_ortofrutta');
INSERT OR IGNORE INTO catalogo (nome, nome_cerca, categoria_id) VALUES ('Arance', 'arance', 'sp_ortofrutta');
INSERT OR IGNORE INTO catalogo (nome, nome_cerca, categoria_id) VALUES ('Mandarini', 'mandarini', 'sp_ortofrutta');
INSERT OR IGNORE INTO catalogo (nome, nome_cerca, categoria_id) VALUES ('Limoni', 'limoni', 'sp_ortofrutta');
INSERT OR IGNORE INTO catalogo (nome, nome_cerca, categoria_id) VALUES ('Pompelmo', 'pompelmo', 'sp_ortofrutta');
INSERT OR IGNORE INTO catalogo (nome, nome_cerca, categoria_id) VALUES ('Kiwi', 'kiwi', 'sp_ortofrutta');
INSERT OR IGNORE INTO catalogo (nome, nome_cerca, categoria_id) VALUES ('Uva', 'uva', 'sp_ortofrutta');
INSERT OR IGNORE INTO catalogo (nome, nome_cerca, categoria_id) VALUES ('Fragole', 'fragole', 'sp_ortofrutta');
INSERT OR IGNORE INTO catalogo (nome, nome_cerca, categoria_id) VALUES ('Ciliegie', 'ciliegie', 'sp_ortofrutta');
INSERT OR IGNORE INTO catalogo (nome, nome_cerca, categoria_id) VALUES ('Pesche', 'pesche', 'sp_ortofrutta');
INSERT OR IGNORE INTO catalogo (nome, nome_cerca, categoria_id) VALUES ('Albicocche', 'albicocche', 'sp_ortofrutta');
INSERT OR IGNORE INTO catalogo (nome, nome_cerca, categoria_id) VALUES ('Susine', 'susine', 'sp_ortofrutta');
INSERT OR IGNORE INTO catalogo (nome, nome_cerca, categoria_id) VALUES ('Melone', 'melone', 'sp_ortofrutta');
INSERT OR IGNORE INTO catalogo (nome, nome_cerca, categoria_id) VALUES ('Anguria', 'anguria', 'sp_ortofrutta');
INSERT OR IGNORE INTO catalogo (nome, nome_cerca, categoria_id) VALUES ('Ananas', 'ananas', 'sp_ortofrutta');
INSERT OR IGNORE INTO catalogo (nome, nome_cerca, categoria_id) VALUES ('Avocado', 'avocado', 'sp_ortofrutta');
INSERT OR IGNORE INTO catalogo (nome, nome_cerca, categoria_id) VALUES ('Melograno', 'melograno', 'sp_ortofrutta');
INSERT OR IGNORE INTO catalogo (nome, nome_cerca, categoria_id) VALUES ('Fichi', 'fichi', 'sp_ortofrutta');
INSERT OR IGNORE INTO catalogo (nome, nome_cerca, categoria_id) VALUES ('Insalata', 'insalata', 'sp_ortofrutta');
INSERT OR IGNORE INTO catalogo (nome, nome_cerca, categoria_id) VALUES ('Lattuga', 'lattuga', 'sp_ortofrutta');
INSERT OR IGNORE INTO catalogo (nome, nome_cerca, categoria_id) VALUES ('Rucola', 'rucola', 'sp_ortofrutta');
INSERT OR IGNORE INTO catalogo (nome, nome_cerca, categoria_id) VALUES ('Radicchio', 'radicchio', 'sp_ortofrutta');
INSERT OR IGNORE INTO catalogo (nome, nome_cerca, categoria_id) VALUES ('Spinaci', 'spinaci', 'sp_ortofrutta');
INSERT OR IGNORE INTO catalogo (nome, nome_cerca, categoria_id) VALUES ('Bietola', 'bietola', 'sp_ortofrutta');
INSERT OR IGNORE INTO catalogo (nome, nome_cerca, categoria_id) VALUES ('Cavolo', 'cavolo', 'sp_ortofrutta');
INSERT OR IGNORE INTO catalogo (nome, nome_cerca, categoria_id) VALUES ('Cavolfiore', 'cavolfiore', 'sp_ortofrutta');
INSERT OR IGNORE INTO catalogo (nome, nome_cerca, categoria_id) VALUES ('Broccoli', 'broccoli', 'sp_ortofrutta');
INSERT OR IGNORE INTO catalogo (nome, nome_cerca, categoria_id) VALUES ('Verza', 'verza', 'sp_ortofrutta');
INSERT OR IGNORE INTO catalogo (nome, nome_cerca, categoria_id) VALUES ('Carote', 'carote', 'sp_ortofrutta');
INSERT OR IGNORE INTO catalogo (nome, nome_cerca, categoria_id) VALUES ('Sedano', 'sedano', 'sp_ortofrutta');
INSERT OR IGNORE INTO catalogo (nome, nome_cerca, categoria_id) VALUES ('Finocchi', 'finocchi', 'sp_ortofrutta');
INSERT OR IGNORE INTO catalogo (nome, nome_cerca, categoria_id) VALUES ('Zucchine', 'zucchine', 'sp_ortofrutta');
INSERT OR IGNORE INTO catalogo (nome, nome_cerca, categoria_id) VALUES ('Melanzane', 'melanzane', 'sp_ortofrutta');
INSERT OR IGNORE INTO catalogo (nome, nome_cerca, categoria_id) VALUES ('Peperoni', 'peperoni', 'sp_ortofrutta');
INSERT OR IGNORE INTO catalogo (nome, nome_cerca, categoria_id) VALUES ('Pomodori', 'pomodori', 'sp_ortofrutta');
INSERT OR IGNORE INTO catalogo (nome, nome_cerca, categoria_id) VALUES ('Pomodorini', 'pomodorini', 'sp_ortofrutta');
INSERT OR IGNORE INTO catalogo (nome, nome_cerca, categoria_id) VALUES ('Pomodori da sugo', 'pomodori da sugo', 'sp_ortofrutta');
INSERT OR IGNORE INTO catalogo (nome, nome_cerca, categoria_id) VALUES ('Cetrioli', 'cetrioli', 'sp_ortofrutta');
INSERT OR IGNORE INTO catalogo (nome, nome_cerca, categoria_id) VALUES ('Patate', 'patate', 'sp_ortofrutta');
INSERT OR IGNORE INTO catalogo (nome, nome_cerca, categoria_id) VALUES ('Patate dolci', 'patate dolci', 'sp_ortofrutta');
INSERT OR IGNORE INTO catalogo (nome, nome_cerca, categoria_id) VALUES ('Cipolle', 'cipolle', 'sp_ortofrutta');
INSERT OR IGNORE INTO catalogo (nome, nome_cerca, categoria_id) VALUES ('Cipollotti', 'cipollotti', 'sp_ortofrutta');
INSERT OR IGNORE INTO catalogo (nome, nome_cerca, categoria_id) VALUES ('Aglio', 'aglio', 'sp_ortofrutta');
INSERT OR IGNORE INTO catalogo (nome, nome_cerca, categoria_id) VALUES ('Porri', 'porri', 'sp_ortofrutta');
INSERT OR IGNORE INTO catalogo (nome, nome_cerca, categoria_id) VALUES ('Zucca', 'zucca', 'sp_ortofrutta');
INSERT OR IGNORE INTO catalogo (nome, nome_cerca, categoria_id) VALUES ('Funghi champignon', 'funghi champignon', 'sp_ortofrutta');
INSERT OR IGNORE INTO catalogo (nome, nome_cerca, categoria_id) VALUES ('Asparagi', 'asparagi', 'sp_ortofrutta');
INSERT OR IGNORE INTO catalogo (nome, nome_cerca, categoria_id) VALUES ('Carciofi', 'carciofi', 'sp_ortofrutta');
INSERT OR IGNORE INTO catalogo (nome, nome_cerca, categoria_id) VALUES ('Fagiolini', 'fagiolini', 'sp_ortofrutta');
INSERT OR IGNORE INTO catalogo (nome, nome_cerca, categoria_id) VALUES ('Piselli freschi', 'piselli freschi', 'sp_ortofrutta');
INSERT OR IGNORE INTO catalogo (nome, nome_cerca, categoria_id) VALUES ('Basilico', 'basilico', 'sp_ortofrutta');
INSERT OR IGNORE INTO catalogo (nome, nome_cerca, categoria_id) VALUES ('Prezzemolo', 'prezzemolo', 'sp_ortofrutta');
INSERT OR IGNORE INTO catalogo (nome, nome_cerca, categoria_id) VALUES ('Rosmarino', 'rosmarino', 'sp_ortofrutta');
INSERT OR IGNORE INTO catalogo (nome, nome_cerca, categoria_id) VALUES ('Salvia', 'salvia', 'sp_ortofrutta');
INSERT OR IGNORE INTO catalogo (nome, nome_cerca, categoria_id) VALUES ('Menta', 'menta', 'sp_ortofrutta');
INSERT OR IGNORE INTO catalogo (nome, nome_cerca, categoria_id) VALUES ('Zenzero', 'zenzero', 'sp_ortofrutta');
INSERT OR IGNORE INTO catalogo (nome, nome_cerca, categoria_id) VALUES ('Peperoncino', 'peperoncino', 'sp_ortofrutta');
INSERT OR IGNORE INTO catalogo (nome, nome_cerca, categoria_id) VALUES ('Frutta di stagione', 'frutta di stagione', 'sp_ortofrutta');
INSERT OR IGNORE INTO catalogo (nome, nome_cerca, categoria_id) VALUES ('Verdura mista', 'verdura mista', 'sp_ortofrutta');
INSERT OR IGNORE INTO catalogo (nome, nome_cerca, categoria_id) VALUES ('Latte intero', 'latte intero', 'sp_freschi');
INSERT OR IGNORE INTO catalogo (nome, nome_cerca, categoria_id) VALUES ('Latte parzialmente scremato', 'latte parzialmente scremato', 'sp_freschi');
INSERT OR IGNORE INTO catalogo (nome, nome_cerca, categoria_id) VALUES ('Latte senza lattosio', 'latte senza lattosio', 'sp_freschi');
INSERT OR IGNORE INTO catalogo (nome, nome_cerca, categoria_id) VALUES ('Panna fresca', 'panna fresca', 'sp_freschi');
INSERT OR IGNORE INTO catalogo (nome, nome_cerca, categoria_id) VALUES ('Panna da cucina', 'panna da cucina', 'sp_freschi');
INSERT OR IGNORE INTO catalogo (nome, nome_cerca, categoria_id) VALUES ('Burro', 'burro', 'sp_freschi');
INSERT OR IGNORE INTO catalogo (nome, nome_cerca, categoria_id) VALUES ('Yogurt bianco', 'yogurt bianco', 'sp_freschi');
INSERT OR IGNORE INTO catalogo (nome, nome_cerca, categoria_id) VALUES ('Yogurt alla frutta', 'yogurt alla frutta', 'sp_freschi');
INSERT OR IGNORE INTO catalogo (nome, nome_cerca, categoria_id) VALUES ('Yogurt greco', 'yogurt greco', 'sp_freschi');
INSERT OR IGNORE INTO catalogo (nome, nome_cerca, categoria_id) VALUES ('Yogurt bambine', 'yogurt bambine', 'sp_freschi');
INSERT OR IGNORE INTO catalogo (nome, nome_cerca, categoria_id) VALUES ('Mozzarella', 'mozzarella', 'sp_freschi');
INSERT OR IGNORE INTO catalogo (nome, nome_cerca, categoria_id) VALUES ('Mozzarella di bufala', 'mozzarella di bufala', 'sp_freschi');
INSERT OR IGNORE INTO catalogo (nome, nome_cerca, categoria_id) VALUES ('Ricotta', 'ricotta', 'sp_freschi');
INSERT OR IGNORE INTO catalogo (nome, nome_cerca, categoria_id) VALUES ('Mascarpone', 'mascarpone', 'sp_freschi');
INSERT OR IGNORE INTO catalogo (nome, nome_cerca, categoria_id) VALUES ('Stracchino', 'stracchino', 'sp_freschi');
INSERT OR IGNORE INTO catalogo (nome, nome_cerca, categoria_id) VALUES ('Formaggio spalmabile', 'formaggio spalmabile', 'sp_freschi');
INSERT OR IGNORE INTO catalogo (nome, nome_cerca, categoria_id) VALUES ('Parmigiano', 'parmigiano', 'sp_freschi');
INSERT OR IGNORE INTO catalogo (nome, nome_cerca, categoria_id) VALUES ('Grana', 'grana', 'sp_freschi');
INSERT OR IGNORE INTO catalogo (nome, nome_cerca, categoria_id) VALUES ('Pecorino', 'pecorino', 'sp_freschi');
INSERT OR IGNORE INTO catalogo (nome, nome_cerca, categoria_id) VALUES ('Provola', 'provola', 'sp_freschi');
INSERT OR IGNORE INTO catalogo (nome, nome_cerca, categoria_id) VALUES ('Emmental', 'emmental', 'sp_freschi');
INSERT OR IGNORE INTO catalogo (nome, nome_cerca, categoria_id) VALUES ('Gorgonzola', 'gorgonzola', 'sp_freschi');
INSERT OR IGNORE INTO catalogo (nome, nome_cerca, categoria_id) VALUES ('Uova', 'uova', 'sp_freschi');
INSERT OR IGNORE INTO catalogo (nome, nome_cerca, categoria_id) VALUES ('Prosciutto crudo', 'prosciutto crudo', 'sp_freschi');
INSERT OR IGNORE INTO catalogo (nome, nome_cerca, categoria_id) VALUES ('Prosciutto cotto', 'prosciutto cotto', 'sp_freschi');
INSERT OR IGNORE INTO catalogo (nome, nome_cerca, categoria_id) VALUES ('Bresaola', 'bresaola', 'sp_freschi');
INSERT OR IGNORE INTO catalogo (nome, nome_cerca, categoria_id) VALUES ('Speck', 'speck', 'sp_freschi');
INSERT OR IGNORE INTO catalogo (nome, nome_cerca, categoria_id) VALUES ('Salame', 'salame', 'sp_freschi');
INSERT OR IGNORE INTO catalogo (nome, nome_cerca, categoria_id) VALUES ('Mortadella', 'mortadella', 'sp_freschi');
INSERT OR IGNORE INTO catalogo (nome, nome_cerca, categoria_id) VALUES ('Wurstel', 'wurstel', 'sp_freschi');
INSERT OR IGNORE INTO catalogo (nome, nome_cerca, categoria_id) VALUES ('Pancetta', 'pancetta', 'sp_freschi');
INSERT OR IGNORE INTO catalogo (nome, nome_cerca, categoria_id) VALUES ('Guanciale', 'guanciale', 'sp_freschi');
INSERT OR IGNORE INTO catalogo (nome, nome_cerca, categoria_id) VALUES ('Petto di pollo', 'petto di pollo', 'sp_freschi');
INSERT OR IGNORE INTO catalogo (nome, nome_cerca, categoria_id) VALUES ('Cosce di pollo', 'cosce di pollo', 'sp_freschi');
INSERT OR IGNORE INTO catalogo (nome, nome_cerca, categoria_id) VALUES ('Carne macinata', 'carne macinata', 'sp_freschi');
INSERT OR IGNORE INTO catalogo (nome, nome_cerca, categoria_id) VALUES ('Fettine di vitello', 'fettine di vitello', 'sp_freschi');
INSERT OR IGNORE INTO catalogo (nome, nome_cerca, categoria_id) VALUES ('Salsiccia', 'salsiccia', 'sp_freschi');
INSERT OR IGNORE INTO catalogo (nome, nome_cerca, categoria_id) VALUES ('Arista', 'arista', 'sp_freschi');
INSERT OR IGNORE INTO catalogo (nome, nome_cerca, categoria_id) VALUES ('Pesce spada', 'pesce spada', 'sp_freschi');
INSERT OR IGNORE INTO catalogo (nome, nome_cerca, categoria_id) VALUES ('Salmone', 'salmone', 'sp_freschi');
INSERT OR IGNORE INTO catalogo (nome, nome_cerca, categoria_id) VALUES ('Salmone affumicato', 'salmone affumicato', 'sp_freschi');
INSERT OR IGNORE INTO catalogo (nome, nome_cerca, categoria_id) VALUES ('Orata', 'orata', 'sp_freschi');
INSERT OR IGNORE INTO catalogo (nome, nome_cerca, categoria_id) VALUES ('Branzino', 'branzino', 'sp_freschi');
INSERT OR IGNORE INTO catalogo (nome, nome_cerca, categoria_id) VALUES ('Gamberi', 'gamberi', 'sp_freschi');
INSERT OR IGNORE INTO catalogo (nome, nome_cerca, categoria_id) VALUES ('Tonno fresco', 'tonno fresco', 'sp_freschi');
INSERT OR IGNORE INTO catalogo (nome, nome_cerca, categoria_id) VALUES ('Pasta fresca', 'pasta fresca', 'sp_freschi');
INSERT OR IGNORE INTO catalogo (nome, nome_cerca, categoria_id) VALUES ('Tortellini', 'tortellini', 'sp_freschi');
INSERT OR IGNORE INTO catalogo (nome, nome_cerca, categoria_id) VALUES ('Ravioli', 'ravioli', 'sp_freschi');
INSERT OR IGNORE INTO catalogo (nome, nome_cerca, categoria_id) VALUES ('Gnocchi', 'gnocchi', 'sp_freschi');
INSERT OR IGNORE INTO catalogo (nome, nome_cerca, categoria_id) VALUES ('Piadine', 'piadine', 'sp_freschi');
INSERT OR IGNORE INTO catalogo (nome, nome_cerca, categoria_id) VALUES ('Pasta sfoglia', 'pasta sfoglia', 'sp_freschi');
INSERT OR IGNORE INTO catalogo (nome, nome_cerca, categoria_id) VALUES ('Pasta brisee', 'pasta brisee', 'sp_freschi');
INSERT OR IGNORE INTO catalogo (nome, nome_cerca, categoria_id) VALUES ('Pizza fresca', 'pizza fresca', 'sp_freschi');
INSERT OR IGNORE INTO catalogo (nome, nome_cerca, categoria_id) VALUES ('Tofu', 'tofu', 'sp_freschi');
INSERT OR IGNORE INTO catalogo (nome, nome_cerca, categoria_id) VALUES ('Hummus', 'hummus', 'sp_freschi');
INSERT OR IGNORE INTO catalogo (nome, nome_cerca, categoria_id) VALUES ('Burrata', 'burrata', 'sp_freschi');
INSERT OR IGNORE INTO catalogo (nome, nome_cerca, categoria_id) VALUES ('Pasta corta', 'pasta corta', 'sp_dispensa');
INSERT OR IGNORE INTO catalogo (nome, nome_cerca, categoria_id) VALUES ('Spaghetti', 'spaghetti', 'sp_dispensa');
INSERT OR IGNORE INTO catalogo (nome, nome_cerca, categoria_id) VALUES ('Penne', 'penne', 'sp_dispensa');
INSERT OR IGNORE INTO catalogo (nome, nome_cerca, categoria_id) VALUES ('Fusilli', 'fusilli', 'sp_dispensa');
INSERT OR IGNORE INTO catalogo (nome, nome_cerca, categoria_id) VALUES ('Riso', 'riso', 'sp_dispensa');
INSERT OR IGNORE INTO catalogo (nome, nome_cerca, categoria_id) VALUES ('Riso basmati', 'riso basmati', 'sp_dispensa');
INSERT OR IGNORE INTO catalogo (nome, nome_cerca, categoria_id) VALUES ('Riso carnaroli', 'riso carnaroli', 'sp_dispensa');
INSERT OR IGNORE INTO catalogo (nome, nome_cerca, categoria_id) VALUES ('Farro', 'farro', 'sp_dispensa');
INSERT OR IGNORE INTO catalogo (nome, nome_cerca, categoria_id) VALUES ('Orzo', 'orzo', 'sp_dispensa');
INSERT OR IGNORE INTO catalogo (nome, nome_cerca, categoria_id) VALUES ('Cous cous', 'cous cous', 'sp_dispensa');
INSERT OR IGNORE INTO catalogo (nome, nome_cerca, categoria_id) VALUES ('Quinoa', 'quinoa', 'sp_dispensa');
INSERT OR IGNORE INTO catalogo (nome, nome_cerca, categoria_id) VALUES ('Farina 00', 'farina 00', 'sp_dispensa');
INSERT OR IGNORE INTO catalogo (nome, nome_cerca, categoria_id) VALUES ('Farina integrale', 'farina integrale', 'sp_dispensa');
INSERT OR IGNORE INTO catalogo (nome, nome_cerca, categoria_id) VALUES ('Farina di mais', 'farina di mais', 'sp_dispensa');
INSERT OR IGNORE INTO catalogo (nome, nome_cerca, categoria_id) VALUES ('Lievito di birra', 'lievito di birra', 'sp_dispensa');
INSERT OR IGNORE INTO catalogo (nome, nome_cerca, categoria_id) VALUES ('Lievito per dolci', 'lievito per dolci', 'sp_dispensa');
INSERT OR IGNORE INTO catalogo (nome, nome_cerca, categoria_id) VALUES ('Zucchero', 'zucchero', 'sp_dispensa');
INSERT OR IGNORE INTO catalogo (nome, nome_cerca, categoria_id) VALUES ('Zucchero di canna', 'zucchero di canna', 'sp_dispensa');
INSERT OR IGNORE INTO catalogo (nome, nome_cerca, categoria_id) VALUES ('Sale fino', 'sale fino', 'sp_dispensa');
INSERT OR IGNORE INTO catalogo (nome, nome_cerca, categoria_id) VALUES ('Sale grosso', 'sale grosso', 'sp_dispensa');
INSERT OR IGNORE INTO catalogo (nome, nome_cerca, categoria_id) VALUES ('Olio extravergine', 'olio extravergine', 'sp_dispensa');
INSERT OR IGNORE INTO catalogo (nome, nome_cerca, categoria_id) VALUES ('Olio di semi', 'olio di semi', 'sp_dispensa');
INSERT OR IGNORE INTO catalogo (nome, nome_cerca, categoria_id) VALUES ('Aceto', 'aceto', 'sp_dispensa');
INSERT OR IGNORE INTO catalogo (nome, nome_cerca, categoria_id) VALUES ('Aceto balsamico', 'aceto balsamico', 'sp_dispensa');
INSERT OR IGNORE INTO catalogo (nome, nome_cerca, categoria_id) VALUES ('Passata di pomodoro', 'passata di pomodoro', 'sp_dispensa');
INSERT OR IGNORE INTO catalogo (nome, nome_cerca, categoria_id) VALUES ('Pelati', 'pelati', 'sp_dispensa');
INSERT OR IGNORE INTO catalogo (nome, nome_cerca, categoria_id) VALUES ('Concentrato di pomodoro', 'concentrato di pomodoro', 'sp_dispensa');
INSERT OR IGNORE INTO catalogo (nome, nome_cerca, categoria_id) VALUES ('Tonno in scatola', 'tonno in scatola', 'sp_dispensa');
INSERT OR IGNORE INTO catalogo (nome, nome_cerca, categoria_id) VALUES ('Sgombro in scatola', 'sgombro in scatola', 'sp_dispensa');
INSERT OR IGNORE INTO catalogo (nome, nome_cerca, categoria_id) VALUES ('Ceci', 'ceci', 'sp_dispensa');
INSERT OR IGNORE INTO catalogo (nome, nome_cerca, categoria_id) VALUES ('Fagioli', 'fagioli', 'sp_dispensa');
INSERT OR IGNORE INTO catalogo (nome, nome_cerca, categoria_id) VALUES ('Lenticchie', 'lenticchie', 'sp_dispensa');
INSERT OR IGNORE INTO catalogo (nome, nome_cerca, categoria_id) VALUES ('Mais', 'mais', 'sp_dispensa');
INSERT OR IGNORE INTO catalogo (nome, nome_cerca, categoria_id) VALUES ('Olive', 'olive', 'sp_dispensa');
INSERT OR IGNORE INTO catalogo (nome, nome_cerca, categoria_id) VALUES ('Capperi', 'capperi', 'sp_dispensa');
INSERT OR IGNORE INTO catalogo (nome, nome_cerca, categoria_id) VALUES ('Sottaceti', 'sottaceti', 'sp_dispensa');
INSERT OR IGNORE INTO catalogo (nome, nome_cerca, categoria_id) VALUES ('Pesto', 'pesto', 'sp_dispensa');
INSERT OR IGNORE INTO catalogo (nome, nome_cerca, categoria_id) VALUES ('Sugo pronto', 'sugo pronto', 'sp_dispensa');
INSERT OR IGNORE INTO catalogo (nome, nome_cerca, categoria_id) VALUES ('Brodo granulare', 'brodo granulare', 'sp_dispensa');
INSERT OR IGNORE INTO catalogo (nome, nome_cerca, categoria_id) VALUES ('Dado', 'dado', 'sp_dispensa');
INSERT OR IGNORE INTO catalogo (nome, nome_cerca, categoria_id) VALUES ('Origano', 'origano', 'sp_dispensa');
INSERT OR IGNORE INTO catalogo (nome, nome_cerca, categoria_id) VALUES ('Pepe', 'pepe', 'sp_dispensa');
INSERT OR IGNORE INTO catalogo (nome, nome_cerca, categoria_id) VALUES ('Curry', 'curry', 'sp_dispensa');
INSERT OR IGNORE INTO catalogo (nome, nome_cerca, categoria_id) VALUES ('Paprika', 'paprika', 'sp_dispensa');
INSERT OR IGNORE INTO catalogo (nome, nome_cerca, categoria_id) VALUES ('Cannella', 'cannella', 'sp_dispensa');
INSERT OR IGNORE INTO catalogo (nome, nome_cerca, categoria_id) VALUES ('Noce moscata', 'noce moscata', 'sp_dispensa');
INSERT OR IGNORE INTO catalogo (nome, nome_cerca, categoria_id) VALUES ('Caffe macinato', 'caffe macinato', 'sp_dispensa');
INSERT OR IGNORE INTO catalogo (nome, nome_cerca, categoria_id) VALUES ('Caffe in cialde', 'caffe in cialde', 'sp_dispensa');
INSERT OR IGNORE INTO catalogo (nome, nome_cerca, categoria_id) VALUES ('Te', 'te', 'sp_dispensa');
INSERT OR IGNORE INTO catalogo (nome, nome_cerca, categoria_id) VALUES ('Tisane', 'tisane', 'sp_dispensa');
INSERT OR IGNORE INTO catalogo (nome, nome_cerca, categoria_id) VALUES ('Camomilla', 'camomilla', 'sp_dispensa');
INSERT OR IGNORE INTO catalogo (nome, nome_cerca, categoria_id) VALUES ('Orzo solubile', 'orzo solubile', 'sp_dispensa');
INSERT OR IGNORE INTO catalogo (nome, nome_cerca, categoria_id) VALUES ('Cacao', 'cacao', 'sp_dispensa');
INSERT OR IGNORE INTO catalogo (nome, nome_cerca, categoria_id) VALUES ('Cioccolato fondente', 'cioccolato fondente', 'sp_dispensa');
INSERT OR IGNORE INTO catalogo (nome, nome_cerca, categoria_id) VALUES ('Cioccolato al latte', 'cioccolato al latte', 'sp_dispensa');
INSERT OR IGNORE INTO catalogo (nome, nome_cerca, categoria_id) VALUES ('Crema di nocciole', 'crema di nocciole', 'sp_dispensa');
INSERT OR IGNORE INTO catalogo (nome, nome_cerca, categoria_id) VALUES ('Marmellata', 'marmellata', 'sp_dispensa');
INSERT OR IGNORE INTO catalogo (nome, nome_cerca, categoria_id) VALUES ('Miele', 'miele', 'sp_dispensa');
INSERT OR IGNORE INTO catalogo (nome, nome_cerca, categoria_id) VALUES ('Biscotti', 'biscotti', 'sp_dispensa');
INSERT OR IGNORE INTO catalogo (nome, nome_cerca, categoria_id) VALUES ('Fette biscottate', 'fette biscottate', 'sp_dispensa');
INSERT OR IGNORE INTO catalogo (nome, nome_cerca, categoria_id) VALUES ('Cereali', 'cereali', 'sp_dispensa');
INSERT OR IGNORE INTO catalogo (nome, nome_cerca, categoria_id) VALUES ('Corn flakes', 'corn flakes', 'sp_dispensa');
INSERT OR IGNORE INTO catalogo (nome, nome_cerca, categoria_id) VALUES ('Muesli', 'muesli', 'sp_dispensa');
INSERT OR IGNORE INTO catalogo (nome, nome_cerca, categoria_id) VALUES ('Crackers', 'crackers', 'sp_dispensa');
INSERT OR IGNORE INTO catalogo (nome, nome_cerca, categoria_id) VALUES ('Grissini', 'grissini', 'sp_dispensa');
INSERT OR IGNORE INTO catalogo (nome, nome_cerca, categoria_id) VALUES ('Taralli', 'taralli', 'sp_dispensa');
INSERT OR IGNORE INTO catalogo (nome, nome_cerca, categoria_id) VALUES ('Pane', 'pane', 'sp_dispensa');
INSERT OR IGNORE INTO catalogo (nome, nome_cerca, categoria_id) VALUES ('Pane in cassetta', 'pane in cassetta', 'sp_dispensa');
INSERT OR IGNORE INTO catalogo (nome, nome_cerca, categoria_id) VALUES ('Pangrattato', 'pangrattato', 'sp_dispensa');
INSERT OR IGNORE INTO catalogo (nome, nome_cerca, categoria_id) VALUES ('Patatine', 'patatine', 'sp_dispensa');
INSERT OR IGNORE INTO catalogo (nome, nome_cerca, categoria_id) VALUES ('Popcorn', 'popcorn', 'sp_dispensa');
INSERT OR IGNORE INTO catalogo (nome, nome_cerca, categoria_id) VALUES ('Frutta secca', 'frutta secca', 'sp_dispensa');
INSERT OR IGNORE INTO catalogo (nome, nome_cerca, categoria_id) VALUES ('Noci', 'noci', 'sp_dispensa');
INSERT OR IGNORE INTO catalogo (nome, nome_cerca, categoria_id) VALUES ('Mandorle', 'mandorle', 'sp_dispensa');
INSERT OR IGNORE INTO catalogo (nome, nome_cerca, categoria_id) VALUES ('Nocciole', 'nocciole', 'sp_dispensa');
INSERT OR IGNORE INTO catalogo (nome, nome_cerca, categoria_id) VALUES ('Pinoli', 'pinoli', 'sp_dispensa');
INSERT OR IGNORE INTO catalogo (nome, nome_cerca, categoria_id) VALUES ('Uvetta', 'uvetta', 'sp_dispensa');
INSERT OR IGNORE INTO catalogo (nome, nome_cerca, categoria_id) VALUES ('Latte di mandorla', 'latte di mandorla', 'sp_dispensa');
INSERT OR IGNORE INTO catalogo (nome, nome_cerca, categoria_id) VALUES ('Latte di soia', 'latte di soia', 'sp_dispensa');
INSERT OR IGNORE INTO catalogo (nome, nome_cerca, categoria_id) VALUES ('Acqua naturale', 'acqua naturale', 'sp_dispensa');
INSERT OR IGNORE INTO catalogo (nome, nome_cerca, categoria_id) VALUES ('Acqua frizzante', 'acqua frizzante', 'sp_dispensa');
INSERT OR IGNORE INTO catalogo (nome, nome_cerca, categoria_id) VALUES ('Succhi di frutta', 'succhi di frutta', 'sp_dispensa');
INSERT OR IGNORE INTO catalogo (nome, nome_cerca, categoria_id) VALUES ('Aranciata', 'aranciata', 'sp_dispensa');
INSERT OR IGNORE INTO catalogo (nome, nome_cerca, categoria_id) VALUES ('Cola', 'cola', 'sp_dispensa');
INSERT OR IGNORE INTO catalogo (nome, nome_cerca, categoria_id) VALUES ('Te freddo', 'te freddo', 'sp_dispensa');
INSERT OR IGNORE INTO catalogo (nome, nome_cerca, categoria_id) VALUES ('Birra', 'birra', 'sp_dispensa');
INSERT OR IGNORE INTO catalogo (nome, nome_cerca, categoria_id) VALUES ('Vino rosso', 'vino rosso', 'sp_dispensa');
INSERT OR IGNORE INTO catalogo (nome, nome_cerca, categoria_id) VALUES ('Vino bianco', 'vino bianco', 'sp_dispensa');
INSERT OR IGNORE INTO catalogo (nome, nome_cerca, categoria_id) VALUES ('Prosecco', 'prosecco', 'sp_dispensa');
INSERT OR IGNORE INTO catalogo (nome, nome_cerca, categoria_id) VALUES ('Tortillas', 'tortillas', 'sp_dispensa');
INSERT OR IGNORE INTO catalogo (nome, nome_cerca, categoria_id) VALUES ('Ketchup', 'ketchup', 'sp_dispensa');
INSERT OR IGNORE INTO catalogo (nome, nome_cerca, categoria_id) VALUES ('Maionese', 'maionese', 'sp_dispensa');
INSERT OR IGNORE INTO catalogo (nome, nome_cerca, categoria_id) VALUES ('Senape', 'senape', 'sp_dispensa');
INSERT OR IGNORE INTO catalogo (nome, nome_cerca, categoria_id) VALUES ('Pannolini taglia 4', 'pannolini taglia 4', 'sp_bambine');
INSERT OR IGNORE INTO catalogo (nome, nome_cerca, categoria_id) VALUES ('Pannolini taglia 5', 'pannolini taglia 5', 'sp_bambine');
INSERT OR IGNORE INTO catalogo (nome, nome_cerca, categoria_id) VALUES ('Pannolini taglia 6', 'pannolini taglia 6', 'sp_bambine');
INSERT OR IGNORE INTO catalogo (nome, nome_cerca, categoria_id) VALUES ('Salviette', 'salviette', 'sp_bambine');
INSERT OR IGNORE INTO catalogo (nome, nome_cerca, categoria_id) VALUES ('Crema cambio', 'crema cambio', 'sp_bambine');
INSERT OR IGNORE INTO catalogo (nome, nome_cerca, categoria_id) VALUES ('Bagnoschiuma bambini', 'bagnoschiuma bambini', 'sp_bambine');
INSERT OR IGNORE INTO catalogo (nome, nome_cerca, categoria_id) VALUES ('Shampoo bambini', 'shampoo bambini', 'sp_bambine');
INSERT OR IGNORE INTO catalogo (nome, nome_cerca, categoria_id) VALUES ('Omogeneizzati', 'omogeneizzati', 'sp_bambine');
INSERT OR IGNORE INTO catalogo (nome, nome_cerca, categoria_id) VALUES ('Biscotti per l infanzia', 'biscotti per l infanzia', 'sp_bambine');
INSERT OR IGNORE INTO catalogo (nome, nome_cerca, categoria_id) VALUES ('Latte crescita', 'latte crescita', 'sp_bambine');
INSERT OR IGNORE INTO catalogo (nome, nome_cerca, categoria_id) VALUES ('Succhi bambini', 'succhi bambini', 'sp_bambine');
INSERT OR IGNORE INTO catalogo (nome, nome_cerca, categoria_id) VALUES ('Merende', 'merende', 'sp_bambine');
INSERT OR IGNORE INTO catalogo (nome, nome_cerca, categoria_id) VALUES ('Budino', 'budino', 'sp_bambine');
INSERT OR IGNORE INTO catalogo (nome, nome_cerca, categoria_id) VALUES ('Snack alla frutta', 'snack alla frutta', 'sp_bambine');
INSERT OR IGNORE INTO catalogo (nome, nome_cerca, categoria_id) VALUES ('Pastina', 'pastina', 'sp_bambine');
INSERT OR IGNORE INTO catalogo (nome, nome_cerca, categoria_id) VALUES ('Dentifricio bambini', 'dentifricio bambini', 'sp_bambine');
INSERT OR IGNORE INTO catalogo (nome, nome_cerca, categoria_id) VALUES ('Cerotti bambini', 'cerotti bambini', 'sp_bambine');
INSERT OR IGNORE INTO catalogo (nome, nome_cerca, categoria_id) VALUES ('Ciucci', 'ciucci', 'sp_bambine');
INSERT OR IGNORE INTO catalogo (nome, nome_cerca, categoria_id) VALUES ('Borotalco', 'borotalco', 'sp_bambine');
INSERT OR IGNORE INTO catalogo (nome, nome_cerca, categoria_id) VALUES ('Piselli surgelati', 'piselli surgelati', 'sp_surgelati');
INSERT OR IGNORE INTO catalogo (nome, nome_cerca, categoria_id) VALUES ('Spinaci surgelati', 'spinaci surgelati', 'sp_surgelati');
INSERT OR IGNORE INTO catalogo (nome, nome_cerca, categoria_id) VALUES ('Minestrone surgelato', 'minestrone surgelato', 'sp_surgelati');
INSERT OR IGNORE INTO catalogo (nome, nome_cerca, categoria_id) VALUES ('Bastoncini di pesce', 'bastoncini di pesce', 'sp_surgelati');
INSERT OR IGNORE INTO catalogo (nome, nome_cerca, categoria_id) VALUES ('Filetti di merluzzo', 'filetti di merluzzo', 'sp_surgelati');
INSERT OR IGNORE INTO catalogo (nome, nome_cerca, categoria_id) VALUES ('Gamberi surgelati', 'gamberi surgelati', 'sp_surgelati');
INSERT OR IGNORE INTO catalogo (nome, nome_cerca, categoria_id) VALUES ('Pizza surgelata', 'pizza surgelata', 'sp_surgelati');
INSERT OR IGNORE INTO catalogo (nome, nome_cerca, categoria_id) VALUES ('Patatine surgelate', 'patatine surgelate', 'sp_surgelati');
INSERT OR IGNORE INTO catalogo (nome, nome_cerca, categoria_id) VALUES ('Gelato', 'gelato', 'sp_surgelati');
INSERT OR IGNORE INTO catalogo (nome, nome_cerca, categoria_id) VALUES ('Ghiaccioli', 'ghiaccioli', 'sp_surgelati');
INSERT OR IGNORE INTO catalogo (nome, nome_cerca, categoria_id) VALUES ('Verdure grigliate surgelate', 'verdure grigliate surgelate', 'sp_surgelati');
INSERT OR IGNORE INTO catalogo (nome, nome_cerca, categoria_id) VALUES ('Funghi surgelati', 'funghi surgelati', 'sp_surgelati');
INSERT OR IGNORE INTO catalogo (nome, nome_cerca, categoria_id) VALUES ('Sofficini', 'sofficini', 'sp_surgelati');
INSERT OR IGNORE INTO catalogo (nome, nome_cerca, categoria_id) VALUES ('Detersivo lavatrice', 'detersivo lavatrice', 'sp_casa');
INSERT OR IGNORE INTO catalogo (nome, nome_cerca, categoria_id) VALUES ('Ammorbidente', 'ammorbidente', 'sp_casa');
INSERT OR IGNORE INTO catalogo (nome, nome_cerca, categoria_id) VALUES ('Detersivo piatti', 'detersivo piatti', 'sp_casa');
INSERT OR IGNORE INTO catalogo (nome, nome_cerca, categoria_id) VALUES ('Detersivo lavastoviglie', 'detersivo lavastoviglie', 'sp_casa');
INSERT OR IGNORE INTO catalogo (nome, nome_cerca, categoria_id) VALUES ('Brillantante', 'brillantante', 'sp_casa');
INSERT OR IGNORE INTO catalogo (nome, nome_cerca, categoria_id) VALUES ('Sale per lavastoviglie', 'sale per lavastoviglie', 'sp_casa');
INSERT OR IGNORE INTO catalogo (nome, nome_cerca, categoria_id) VALUES ('Sgrassatore', 'sgrassatore', 'sp_casa');
INSERT OR IGNORE INTO catalogo (nome, nome_cerca, categoria_id) VALUES ('Candeggina', 'candeggina', 'sp_casa');
INSERT OR IGNORE INTO catalogo (nome, nome_cerca, categoria_id) VALUES ('Anticalcare', 'anticalcare', 'sp_casa');
INSERT OR IGNORE INTO catalogo (nome, nome_cerca, categoria_id) VALUES ('Detergente pavimenti', 'detergente pavimenti', 'sp_casa');
INSERT OR IGNORE INTO catalogo (nome, nome_cerca, categoria_id) VALUES ('Detergente vetri', 'detergente vetri', 'sp_casa');
INSERT OR IGNORE INTO catalogo (nome, nome_cerca, categoria_id) VALUES ('Carta igienica', 'carta igienica', 'sp_casa');
INSERT OR IGNORE INTO catalogo (nome, nome_cerca, categoria_id) VALUES ('Rotoloni da cucina', 'rotoloni da cucina', 'sp_casa');
INSERT OR IGNORE INTO catalogo (nome, nome_cerca, categoria_id) VALUES ('Tovaglioli di carta', 'tovaglioli di carta', 'sp_casa');
INSERT OR IGNORE INTO catalogo (nome, nome_cerca, categoria_id) VALUES ('Fazzoletti', 'fazzoletti', 'sp_casa');
INSERT OR IGNORE INTO catalogo (nome, nome_cerca, categoria_id) VALUES ('Sacchi umido', 'sacchi umido', 'sp_casa');
INSERT OR IGNORE INTO catalogo (nome, nome_cerca, categoria_id) VALUES ('Sacchi spazzatura', 'sacchi spazzatura', 'sp_casa');
INSERT OR IGNORE INTO catalogo (nome, nome_cerca, categoria_id) VALUES ('Sacchi differenziata', 'sacchi differenziata', 'sp_casa');
INSERT OR IGNORE INTO catalogo (nome, nome_cerca, categoria_id) VALUES ('Pellicola trasparente', 'pellicola trasparente', 'sp_casa');
INSERT OR IGNORE INTO catalogo (nome, nome_cerca, categoria_id) VALUES ('Carta forno', 'carta forno', 'sp_casa');
INSERT OR IGNORE INTO catalogo (nome, nome_cerca, categoria_id) VALUES ('Carta alluminio', 'carta alluminio', 'sp_casa');
INSERT OR IGNORE INTO catalogo (nome, nome_cerca, categoria_id) VALUES ('Spugne', 'spugne', 'sp_casa');
INSERT OR IGNORE INTO catalogo (nome, nome_cerca, categoria_id) VALUES ('Panni cattura polvere', 'panni cattura polvere', 'sp_casa');
INSERT OR IGNORE INTO catalogo (nome, nome_cerca, categoria_id) VALUES ('Guanti', 'guanti', 'sp_casa');
INSERT OR IGNORE INTO catalogo (nome, nome_cerca, categoria_id) VALUES ('Strofinacci', 'strofinacci', 'sp_casa');
INSERT OR IGNORE INTO catalogo (nome, nome_cerca, categoria_id) VALUES ('Deodorante ambiente', 'deodorante ambiente', 'sp_casa');
INSERT OR IGNORE INTO catalogo (nome, nome_cerca, categoria_id) VALUES ('Insetticida', 'insetticida', 'sp_casa');
INSERT OR IGNORE INTO catalogo (nome, nome_cerca, categoria_id) VALUES ('Lampadine', 'lampadine', 'sp_casa');
INSERT OR IGNORE INTO catalogo (nome, nome_cerca, categoria_id) VALUES ('Pile', 'pile', 'sp_casa');
INSERT OR IGNORE INTO catalogo (nome, nome_cerca, categoria_id) VALUES ('Sapone mani', 'sapone mani', 'sp_casa');
INSERT OR IGNORE INTO catalogo (nome, nome_cerca, categoria_id) VALUES ('Bagnoschiuma', 'bagnoschiuma', 'sp_casa');
INSERT OR IGNORE INTO catalogo (nome, nome_cerca, categoria_id) VALUES ('Shampoo', 'shampoo', 'sp_casa');
INSERT OR IGNORE INTO catalogo (nome, nome_cerca, categoria_id) VALUES ('Balsamo', 'balsamo', 'sp_casa');
INSERT OR IGNORE INTO catalogo (nome, nome_cerca, categoria_id) VALUES ('Dentifricio', 'dentifricio', 'sp_casa');
INSERT OR IGNORE INTO catalogo (nome, nome_cerca, categoria_id) VALUES ('Spazzolino', 'spazzolino', 'sp_casa');
INSERT OR IGNORE INTO catalogo (nome, nome_cerca, categoria_id) VALUES ('Filo interdentale', 'filo interdentale', 'sp_casa');
INSERT OR IGNORE INTO catalogo (nome, nome_cerca, categoria_id) VALUES ('Deodorante', 'deodorante', 'sp_casa');
INSERT OR IGNORE INTO catalogo (nome, nome_cerca, categoria_id) VALUES ('Rasoi', 'rasoi', 'sp_casa');
INSERT OR IGNORE INTO catalogo (nome, nome_cerca, categoria_id) VALUES ('Schiuma da barba', 'schiuma da barba', 'sp_casa');
INSERT OR IGNORE INTO catalogo (nome, nome_cerca, categoria_id) VALUES ('Assorbenti', 'assorbenti', 'sp_casa');
INSERT OR IGNORE INTO catalogo (nome, nome_cerca, categoria_id) VALUES ('Cotone', 'cotone', 'sp_casa');
INSERT OR IGNORE INTO catalogo (nome, nome_cerca, categoria_id) VALUES ('Cerotti', 'cerotti', 'sp_casa');
INSERT OR IGNORE INTO catalogo (nome, nome_cerca, categoria_id) VALUES ('Alcol', 'alcol', 'sp_casa');
INSERT OR IGNORE INTO catalogo (nome, nome_cerca, categoria_id) VALUES ('Disinfettante', 'disinfettante', 'sp_casa');
INSERT OR IGNORE INTO catalogo (nome, nome_cerca, categoria_id) VALUES ('Sacchetti aspirapolvere', 'sacchetti aspirapolvere', 'sp_casa');
